# Generated by Django 5.0.7 on 2024-09-02 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(default='asasadsad@asasassa.com', max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
